# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Instalar dependências
        run: npm install

      - name: Compilar e empacotar aplicação
        run: npm run build --if-present

      - name: Deploy da Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'estensinaapp'
          package: .
